name: Build EXE with PyInstaller

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 拉取仓库代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.5"

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      # 使用 pyinstaller 生成 spec 文件
      - name: Generate .spec file
        run: |
          pyinstaller --name myapp --icon=icon.ico --onedir --specpath . main.py

      # 使用 spec 文件打包 exe
      - name: Build EXE from spec
        run: |
          pyinstaller myapp.spec

      # 上传构建好的 exe
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-exe
          path: dist/myapp/
