name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Package Windows Executable with Docker
      run: |
        docker run --rm -v "${{ github.workspace }}:/src" ghcr.io/pyinstaller/pyinstaller:python3.10 pyinstaller /src/main.spec --platform=win64
    
    - name: Upload Windows Executable
      uses: actions/upload-artifact@v4
