name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.5' # 根据你的项目需要调整Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller # 安装pyinstaller

    - name: Package Windows Executable
      run: |
        docker pull cdgriffith/pyinstaller-windows:python3.10-win64 # 拉取Windows 64位打包镜像
        docker run --rm -v "${{ github.workspace }}:/src" cdgriffith/pyinstaller-windows:python3.10-win64 pyinstaller /src/main.spec

    - uses: actions/upload-artifact@v4
      with:
        name: your-app-name-windows-exe
        path: dist/main.exe
